Create formatter for phone numbers.
Medology/FlexibleMink pull request #357
Opened 2021-02-23 22:00 UTC by juanmrad

Story:
We don't have a way to format phone inputs on flexible mink store when the value displayed on front-end is different from the one capture on the DB when requesting.

Solution:
Add a way to format phone numbers on US format and ###-###-#### as used on some places.
add tests.

2021-02-26 19:59 UTC, aserv92 requested changes

2021-02-26 19:59 UTC, aserv92 commented on .circleci/config.yml
> +      image: ubuntu-1604:202007-01
Consider using a newer image like `ubuntu-1604:202101-01`.
We should also consider overcoming the challenges related to the Ubuntu 20 images for CircleCI, as it seems there is only going to be one more Ubuntu 16 update.
https://circleci.com/docs/2.0/configuration-reference/#available-machine-images

2021-02-26 19:59 UTC, aserv92 commented on src/Medology/Behat/StoreContext.php
>       * @return mixed the prepared value
I know you haven't changed the return type of this method but it would be nice to document what the expected return types are. if possible.

2021-03-01 14:36 UTC, johnnie502 approved these changes

2021-03-01 16:23 UTC, izazueta approved these changes

2021-03-03 15:16 UTC, juanmrad commented on src/Medology/Behat/StoreContext.php
>       * @return mixed the prepared value
it depends on the properties of the format mapper. `$format_map` right now it is just strings and arrays, but that could change.

2021-03-03 16:18 UTC, aserv92 approved these changes

2021-03-03 16:27 UTC, merged