Additional times
Medology/FlexibleMink pull request #388
Opened 2021-09-07 15:17 UTC by BKorenek

For: #something

BUG FIX:

**Cause:**

**Solution:**

FEATURE IMPLEMENTATION:

Whatever you want (screenshots, etc)

2021-09-07 16:12 UTC, aserv92 requested changes
Please add some tests, and write a description for this PR.

2021-09-07 16:12 UTC, aserv92 commented on src/Medology/Behat/StoreContext.php
> -        'a US time with seconds'          => 'h:i:s',
I'm don't think we should remove this unless we know that no other projects are using this.

2021-09-07 16:13 UTC, aserv92 requested changes
.

2021-09-07 16:32 UTC, izazueta requested changes
What Andrew said

2021-09-07 16:32 UTC, izazueta requested changes
.

2021-09-07 17:39 UTC, BKorenek commented on src/Medology/Behat/StoreContext.php
> -        'a US time with seconds'          => 'h:i:s',
Remove what? Testing is already in place for this feature. This is simply adding in additional formatting options.

2021-09-07 17:57 UTC, BKorenek commented on src/Medology/Behat/StoreContext.php
> -        'a US time with seconds'          => 'h:i:s',
just realized you are looking at the one specific line. Yeah, that was added in by me and is not in use anywhere

2021-09-07 18:52 UTC, PayneWheat approved these changes
. (just wanted to fit in)

2021-09-07 18:53 UTC, PayneWheat approved these changes
.. (pull approve is buggy)

2021-09-08 13:22 UTC, izazueta approved these changes

2021-09-08 15:48 UTC, aserv92 approved these changes

2021-09-08 15:52 UTC, merged