Chaning time formats
Medology/FlexibleMink pull request #390
Opened 2021-09-13 14:34 UTC by BKorenek

This will adjust time formats to show single digit hours instead of multiple. E.g. 06:12 PM vs 6:12PM

2021-09-13 16:29 UTC, aserv92 requested changes
It seems like this change assumes that none of our applications have the desired functionality of showing times with double-digit hours

2021-09-13 16:30 UTC, aserv92 requested changes
.

2021-09-13 16:52 UTC, fortoulrodolfo approved these changes

2021-09-13 16:53 UTC, fortoulrodolfo commented
@aserv92 Correct, but whenever we update the flexiblemink version in our projects, the tests are going to fail and we need to adjust that assumption there. (If we have test for everything :trollface: )

2021-09-13 17:21 UTC, fortoulrodolfo approved these changes

2021-09-14 15:34 UTC, aserv92 approved these changes

2021-09-14 15:55 UTC, merged