Feature: Inject dynamic relative dates into steps
Medology/FlexibleMink pull request #400
Opened 2021-09-29 22:06 UTC by Chekote

2021-10-02 13:22 UTC, Chekote commented
Scrutinizer's complaints are all false positives complaining about dependencies missing when they are not. I have already filed a bug with them.

2021-10-02 19:32 UTC, Chekote commented
@BKorenek I'm just requesting a review from you first because I want to make sure you are happy with this implementation before I have anyone else take a look at it.

2021-10-04 14:21 UTC, PayneWheat commented
I'll hold off on reviewing this until Brandon takes a look.

2021-10-04 15:25 UTC, BKorenek commented on src/Medology/Behat/DateInjector.php
> +}
WTB line break

2021-10-04 15:25 UTC, BKorenek commented on features/DateInjector.feature
> +    | The first Saturday was (a date/time of 'First Saturday')         | The first Saturday was 2022-10-29 00:00:00     |
Will this work with the `formatted as ` functionality? that would be necessary on my end. Also, something like `now - 1 month`? The scenario I'm in is I select last month, and I need to assert that the beginning of last month appears on the page formatted as a MySQL timestamp and the end also

2021-10-04 15:25 UTC, BKorenek commented on src/Medology/Behat/DateInjector.php
> +    public function injectCarbonStrings(string $subject): string {
now that I understand what the meaning of inject is, it's not so hard to wrap my head around but if we wanted to go with an alternative because I didn't get it we could do something like format string, parseStringTemplate etc. One of the biggest confusions I had tho I think was because it was a method on the store itself, so I conflated injection with injection into the store

2021-10-04 16:54 UTC, aserv92 requested changes
Just some minor style changes.

2021-10-04 16:54 UTC, aserv92 commented on src/Medology/Behat/StoreContext.php
> +    {
```suggestion
    public function gatherContexts(BeforeScenarioScope $scope): void {
```

2021-10-04 16:54 UTC, aserv92 commented on src/Medology/Behat/Traits/GathersContexts.php
> +    {
There are a few instances of the opening curly bracket being on the wrong line. Is the style fixer doing this? Maybe the style fixer isn't working on this project.

```suggestion
    public function getEnvironment(BeforeScenarioScope $scope): InitializedContextEnvironment {
```

2021-10-04 16:54 UTC, aserv92 commented on tests/Medology/Behat/DateInjector/DateInjectorTest.php
> +    {
```suggestion
    public function tearDown(): void {
```

2021-10-04 17:28 UTC, Chekote commented on src/Medology/Behat/DateInjector.php
> +    public function injectCarbonStrings(string $subject): string {
The inject method on the store doesn't inject anything into the store. It injects values from the store into a string, just like this injects dates into a string. So it is consistent.

2021-10-04 18:46 UTC, Chekote commented on features/DateInjector.feature
> +    | The first Saturday was (a date/time of 'First Saturday')         | The first Saturday was 2022-10-29 00:00:00     |
It should work with formatted as. I will add a test to cover that and ensure that it does.

I do not know if "now - 1 month" will work. As per our initial discussion of the acceptance criteria, I am simply exposing the functionality of the Carbon::parse method. So if that string works with Carbon::parse, then it will work here.

2021-10-04 19:01 UTC, Chekote commented on features/DateInjector.feature
> +    | The first Saturday was (a date/time of 'First Saturday')         | The first Saturday was 2022-10-29 00:00:00     |
Good catch on the `formatted as`. It wasn't working properly I'll have an update pushed in just a moment.

2021-10-04 20:27 UTC, Chekote commented
I have fixed all legitimate Scrutinizer complaints. All the remaining complaints are due to a Scrutinizer bug where it cannot find dependencies, which has already been reported to them.

2021-10-04 20:50 UTC, aserv92 approved these changes

2021-10-04 20:54 UTC, aserv92 reviewed
Since you updated the Circle CI configuration and removed support for php5 can you please update the GitHub merge requirements for this repo after you merge this PR.
![Screen Shot 2021-10-04 at 3 52 08 PM](https://user-images.githubusercontent.com/29462945/135923425-5213dfd4-63c9-4144-a0f3-8adce4c273f1.png)

2021-10-04 21:06 UTC, PayneWheat approved these changes

2021-10-05 13:37 UTC, BKorenek approved these changes

2021-10-05 14:47 UTC, Chekote commented
@aserv92 yeah, I was going to do that. I just didn't want to do so until this was ready to merge just in case anyone objected to dropping PHP5 support.

2021-10-05 16:28 UTC, VitorTS approved these changes

2021-10-05 18:15 UTC, merged