Update expected values on CSVContext to use stored values
Medology/FlexibleMink pull request #415
Opened 2021-12-08 17:01 UTC by oliveiraweb

For: #414 

BUG FIX:
Now Developers can assert the CSV response contains values from the model.

**Solution:**
Implemented updateExpectedDataAndInjectValues function on CsvContext to update the expected value.

2021-12-09 21:45 UTC, Chekote requested changes

2021-12-10 15:44 UTC, aserv92 requested changes
Nice job, just a minor change.

2021-12-10 15:44 UTC, aserv92 commented on src/Medology/Behat/CsvContext.php
> +     * @throws ReflectionException
Please add missing information to this docblock.

```suggestion
     *
     * @param TableNode                 $table A table node containing the values to inject.
     * @throws ReflectionException When {the reason why the exception was thrown}
```

2021-12-10 19:38 UTC, aserv92 requested changes

2021-12-10 19:38 UTC, aserv92 commented on src/Medology/Behat/CsvContext.php
> +     * @throws ReflectionException When {the reason why the exception was thrown}
Sorry if I confused you. The part that I put in curly brackets was meant to be changed to explain why the exception was thrown.

2021-12-10 20:13 UTC, oliveiraweb commented on src/Medology/Behat/CsvContext.php
> +     * @throws ReflectionException When {the reason why the exception was thrown}
I forgot it haha, sorry

2021-12-10 20:32 UTC, johnnie502 commented on src/Medology/Behat/CsvContext.php
> +        $tableNode = new TableNode($expectedData);
I am wondering if creating the TableNode object is necessary? It is converted to array when returns seems we don't need to let it go thru TableNode again

2021-12-13 13:46 UTC, johnnie502 requested changes

2021-12-13 13:46 UTC, johnnie502 commented on src/Medology/Behat/CsvContext.php
> +        $expectedData = array_map(function ($row) {
Seems the code block has been duplicated, please remove line 138-143

2021-12-13 14:37 UTC, Chekote requested changes

2021-12-13 14:37 UTC, Chekote commented on src/Medology/Behat/CsvContext.php
> +        return array_values($expectedData);
You could avoid the overhead of assigning and garbage-collecting a variable by using array_values inline:

```suggestion
        return array_values(array_map(function ($row) {
            return array_map(function ($value) {
                return $this->storeContext->injectStoredValues($value);
            }, $row);
        }, $table->getRows()));
```

If you are mapping an array using a function on an object, you can further simplify this and avoid the additional nested function by using an [object method callback](https://www.php.net/manual/en/language.types.callable.php):

```php
        return array_values(array_map(function ($row) {
            return array_map([$this->storeContext, 'injectStoredValues'], $row);
        }, $table->getRows()));
```

Unfortunately, the project currently supports < PHP 7.4, so we can't use [arrow functions](https://www.php.net/manual/en/functions.arrow.php) to simplify it further 😞

2021-12-13 14:37 UTC, Chekote commented on src/Medology/Behat/CsvContext.php
> +    private function updateExpectedDataAndInjectValues(TableNode $table): array
I don't feel like this is a good name for this method. Firstly, it seems to only be injecting stored values. I am not sure what you mean by "update expected data". Secondly, having the word "And" in a method is a [code smell](https://en.wikipedia.org/wiki/Code_smell) and indicates that you are violating [SRP](https://en.wikipedia.org/wiki/Single-responsibility_principle) (which as far as I can tell, you aren't).

Also, I don't think this is a good location for the method, given what it is doing. It is injecting stored values into a TableNode. That seems like quite a useful and general-purpose piece of functionality, and therefore should not be hidden away inside something as specific as a CSV Context class.

Since the `injectStoredValues` is a method on the `StoreContext` class, and the `StoreContext` class is already something that is tightly coupled to Behat, I feel we should move this method to the `StoreContext` and rename it to `injectStoredValuesTable`

2021-12-13 14:37 UTC, Chekote commented on src/Medology/Behat/CsvContext.php
> +     * @throws ReflectionException When injected parameters are invalid
There are many more exceptions that can bubble up from `injectStoredValues`. If you are not swallowing or transforming them in any way, you should have the exact same `@throws` here as the method(s) you are calling.

2021-12-13 14:37 UTC, Chekote commented on src/Medology/Behat/CsvContext.php
> +     * Update expected data injecting model values.
When you move this method, please also update this description:

```suggestion
     * Parses each TableNode cell for references to stored items and replaces them with the value from the store.
```

2021-12-13 14:37 UTC, Chekote commented on src/Medology/Behat/CsvContext.php
> +     * @param TableNode $table a table node containing the values to inject
The table does not contain values to inject. Values are being injected into it.

```suggestion
     * @param TableNode $table a table node containing the values to parse
```

2021-12-13 18:05 UTC, Chekote requested changes

2021-12-13 18:05 UTC, Chekote commented on src/Medology/Behat/StoreContext.php
> +        }, $table->getRows()));
It seems you missed the second part of my [previous suggestion](https://github.com/Medology/FlexibleMink/pull/415#discussion_r767805228).

```suggestion
        return array_values(array_map(function ($row) {
            return array_map([$this->storeContext, 'injectStoredValues'], $row);
        }, $table->getRows()));
```

2021-12-14 13:40 UTC, Chekote approved these changes

2021-12-14 15:16 UTC, gamanuel approved these changes

2021-12-14 16:44 UTC, aserv92 approved these changes

2021-12-14 22:14 UTC, johnnie502 approved these changes

2021-12-16 17:28 UTC, aserv92 approved these changes

2021-12-16 17:38 UTC, johnnie502 approved these changes

2021-12-17 14:00 UTC, Chekote approved these changes

2021-12-17 15:52 UTC, gamanuel approved these changes

2021-12-17 16:18 UTC, merged