Extract NounStore class from StoreContext.
Medology/FlexibleMink pull request #440
Opened 2022-03-17 01:18 UTC by lorenzodalaqua

For: https://github.com/Medology/Umami/issues/424

We are planning on reusing functionality from Behat tests to expose an API to create preconditions for tests from other projects that rely on the API in STDCheck. Most Behat tests in STDCheck rely on functionality from `StoreContext` in FlexibleMink.

To separate logic to create these preconditions from Behat context classes I have extracted the `Medology\Behat\NounStore` class with the functionality from `StoreContext` that may be reused outside of a Behat test suite. 

`StoreContext` previously extended the `Chekote\NounStore\Store` class, now the new `NounStore` is the one that extends the store, and backwards compatibility for current usage of the `StoreContext` class was kept by using the `__call` magic method to delegate calls to the new `NounStore` class.

2022-03-17 13:03 UTC, Chekote requested changes
Looks good. We just need to update the testing to cover the new NounStore class and the new proxy feature of the StoreContext class.

2022-03-17 13:03 UTC, Chekote commented on tests/Medology/Behat/StoreContextTest.php
>      }
The majority of the methods being tested here are now on the NounStore class rather than StoreContext. Please create a NounStoreTest class and move the appropriate tests there, and test the methods on that class directly.

For the methods that should be able to be proxied to NounStore through StoreContext, please add tests to the StoreContextTest class that mock out the NounStore, and then attempt to call the method and verify that the method was called on the mock.

2022-03-17 14:17 UTC, lorenzodalaqua commented on tests/Medology/Behat/StoreContextTest.php
>      }
Taking a better look at these test classes, it seems there is a lot of unused code and a few methods aren't even tested, will add tests for all methods and add the  'Do not review'  for now until you approve it.

2022-03-17 14:30 UTC, Chekote commented on tests/Medology/Behat/StoreContextTest.php
>      }
FYI: Adding tests for the methods you moved is reasonable. But if you didn't touch a method that is missing tests, you don't have to write tests for it. Yes, we want to get decent coverage, but filling out missing tests for code you didn't touch is outside of your scope of work.

2022-03-17 14:34 UTC, lorenzodalaqua commented on tests/Medology/Behat/StoreContextTest.php
>      }
Ok, just thought since I was changing things I could improve the codebase, but I'll just separate the tests for each class, remove the unused code and leave things a bit cleaner then.

2022-03-17 17:56 UTC, Chekote submitted a review, later dismissed

2022-03-18 15:47 UTC, fortoulrodolfo requested changes
All looks good to me. I only have 1 question. Great work btw. 👍

2022-03-18 15:47 UTC, fortoulrodolfo commented on src/Medology/Behat/NounStore.php
> +namespace Medology\Behat;
Since this class will be used for diff purposes, should we still keep it in the `/Behat` directory? 🤔

2022-03-18 17:16 UTC, PayneWheat submitted a review, later dismissed

2022-03-18 19:50 UTC, lorenzodalaqua commented on src/Medology/Behat/NounStore.php
> +namespace Medology\Behat;
I don't see a reason, will take it out of that directory like the Spinner class in this package, will make it clear this is not related to Behat. Not sure if the Medology namespace is okay to use, but I suppose it does not have a NounStore class yet.

2022-03-18 20:47 UTC, fortoulrodolfo approved these changes

2022-03-18 20:48 UTC, fortoulrodolfo submitted a review, later dismissed

2022-03-21 12:10 UTC, Chekote commented on src/Medology/Behat/NounStore.php
> +namespace Medology\Behat;
Good catch @fortoulrodolfo 👏

2022-03-21 12:11 UTC, Chekote approved these changes

2022-03-21 13:54 UTC, PayneWheat approved these changes

2022-03-21 15:10 UTC, lorenzodalaqua commented
Requesting force merge because Scrutinizer issues seems to be dependencies are misconfigured somehow, it cannot find some referenced classes from composer packages.

2022-03-21 15:17 UTC, merged